language: node_js
os: linux
dist: focal
arch: amd64
jobs:
  include:
    - name: JavaScript driver
      node_js: 16
      services:
        - postgresql
      addons:
        postgresql: 12
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
      env:
        global:
          - PGVERSION=12
          - PGPORT=5432
      script:
        - npm install
        - npm run lint
        - npm run build
        - npm run test
after_success:
  - NODE_ENV=test nyc npm run test
  - nyc check-coverage --lines 50
  - nyc report --reporter=text-lcov | coveralls
  - npm run build
  - semantic-release
notifications:
  email: false
before_install:
  - sudo sed -i '/^host\s*all/ s/md5/trust/' /etc/postgresql/12/main/pg_hba.conf
  - sudo service postgresql restart $PGVERSION;
  - until pg_isready -p 5433; do echo 'Waiting for the DB to be up...'; sleep 1; done;
