language: node_js
node_js:
  - 8
script:
  - npm run build
  - npm run test
  - npm run lint
  - NODE_ENV=test nyc --silent ava
  - nyc report --reporter=text-lcov | coveralls
  - nyc check-coverage --lines 70
after_success:
  - npm run build
  - semantic-release pre
  - npm publish
  - semantic-release post
notifications:
  email: false
sudo: false
