language: node_js
os: linux
dist: focal
arch: amd64
jobs:
  include:
    - name: JavaScript driver
      node_js: 14
      services:
        - postgresql
      addons:
        postgresql: 12
        apt:
          packages:
            - postgresql-12
            - postgresql-client-12
      env:
        global:
          - PGPORT=5432
      script:
        - sudo pg_ctlcluster 12 main restart
        - npm install
        - npm run build
        - npm run test
        - nyc report --reporter=text-lcov | coveralls
        - nyc check-coverage --lines 50
after_success:
  - npm run lint
  - NODE_ENV=test nyc npm run test
  - nyc report --reporter=text-lcov | coveralls
  - npm run build
  - semantic-release
notifications:
  email: false
sudo: false
