language: node_js
jobs:
  include:
    - node_js: '10'
      addons:
        postgresql: '9.6'
script:
  - npm run build
  - NODE_ENV=test nyc npm run test
  - npm run lint
  - nyc report --reporter=text-lcov | coveralls
  - nyc check-coverage --lines 50
after_success:
  - npm run build
  - semantic-release
notifications:
  email: false
sudo: false
